url: http://www.jenadevs.org
baseurl: 

# Site settings
title: jenadevs.org
email: jena@softwerkskammer.org
description: "Softwerkskammer Jena is a local Software Craftsmanship Community. We do talks, workshops & coding dojos. Our jenadevs meetup takes place monthly."


# Team names, titles and social links
people:
- name: Benjamin Nothdurft
  pic: 1
  position: Organizer, DevOps, Continuous Delivery, Java Stack, Test Automation, Docker
  social:
    - title: twitter
      url: http://twitter.com/dataduke
    - title: github
      url: http://github.com/dataduke
    - title: linkedin
      url: http://www.linkedin.com/in/dataduke

- name: Oliver Zscheyge
  pic: 2
  position: Organizer, Backend Developer, Functional Programming, Python, Vim 
  social:
    - title: twitter
      url: http://twitter.com/oozpy
    - title: github
      url: http://github.com/ooz

- name: Andreas Grohman
  pic: 3
  position: Organizer, Backend Developer, Ruby on Rails, Perl, Android
  social:
    - title: twitter
      url: http://twitter.com/oozpy
    - title: github
      url: http://github.com/agrohmann

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jenadevs
  - title: github
    url: http://github.com/jenadevs

# Postal address (add as many lines as necessary)
address:
  - line: Heinrich-Heine-Str. 1
  - line: Jena, Germany

# Build settings
markdown: kramdown
permalink: pretty
