url: http://www.jenadevs.org
baseurl: 

# Site settings
title: jenadevs Meetup
email: jena@softwerkskammer.org
description: "Softwerkskammer Jena is a local Software Craftsmanship Community. We do talks, workshops & coding dojos. Our jenadevs meetup takes place monthly."


# Team names, titles and social links
people:
- name: Benjamin Nothdurft
  pic: 1
  position: Organizer, DevOps, Continuous Delivery, Java Stack, Test Automation, Docker
  social:
    - title: medium
      url: http://www.medium.com/dataduke
    - title: twitter
      url: http://www.twitter.com/dataduke
    - title: github
      url: http://www.github.com/dataduke
    - title: facebook
      url: http://www.facebook.com/dataduke
    - title: linkedin
      url: http://www.linkedin.com/in/dataduke
    - title: xing
      url: http://www.xing.to/dataduke

- name: Oliver Zscheyge
  pic: 2
  position: Organizer, Backend Developer, Functional Programming, Python, Vim 
  social:
    - title: twitter
      url: http://www.twitter.com/oozpy
    - title: github
      url: http://www.github.com/ooz

- name: Andreas Grohman
  pic: 3
  position: Organizer, Senior Software Engineer, Ruby on Rails, Docker, Microservices, CoreOS, Perl, Android
  social:
    - title: medium
      url: http://www.andreas-grohmann.com/
    - title: twitter
      url: http://www.twitter.com/grohmeo
    - title: github
      url: http://www.github.com/agrohmann
    - title: facebook
      url: http://www.facebook.com/andreas.grohmann
    - title: linkedin
      url: http://www.linkedin.com/in/andreas-grohmann
    - title: xing
      url: http://www.xing.com/profile/Andreas_Grohmann7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://www.twitter.com/jenadevs
  - title: github
    url: http://www.github.com/jenadevs

# Postal address (add as many lines as necessary)
address:
  - line: Heinrich-Heine-Str. 1
  - line: Jena, Germany

# Build settings
markdown: kramdown
permalink: pretty
