url: https://jenadevs.github.io
# baseurl: /softwerkskammer/

# Site settings
title: Softwerkskammer Jena
email: your-email@domain.com
description: "Softwerkskammer Jena is a local Software Craftsmanship Community. We do talks, workshops & coding dojos. Our jenadevs meetup takes place monthly."


# Team names, titles and social links
people:
- name: Benjamin Nothdurft
  pic: 1
  position: Organiser
  social:
    - title: twitter
      url: http://twitter.com/dataduke
    - title: github
      url: http://github.com/dataduke
    - title: linkedin
      url: http://www.linkedin.com/in/dataduke

- name: Oliver Zscheyge
  pic: 2
  position: Organiser
  social:
    - title: twitter
      url: http://twitter.com/oozpy
    - title: github
      url: http://github.com/ooz

- name: Andreas Grohman
  pic: 3
  position: Organiser
  social:
    - title: twitter
      url: http://twitter.com/oozpy
    - title: github
      url: http://github.com/agrohmann

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/jenadevs
  - title: github
    url: http://github.com/jenadevs

# Postal address (add as many lines as necessary)
address:
  - line: Heinrich-Heine-Str. 1
  - line: Jena, Germany

# Build settings
markdown: kramdown
permalink: pretty
